# Generated by Django 4.1 on 2022-09-02 11:00

import binascii
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=122)),
                ('status', models.CharField(default=binascii.Incomplete, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='taskpro',
        ),
    ]
