# Generated by Django 4.1 on 2022-09-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_tsk_delete_taskpro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsk',
            name='status',
            field=models.CharField(default='Incomplete', max_length=100),
        ),
    ]
